# docker version
#
version: '3.8'

# isolated virtual containers
#
services:

  # mongodb: download latest mongo image
  #
  mongodb:
    image: mongo:8
    container_name: via_mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # backend: build backend image
  #
  backend:
    build: ./backend
    container_name: via_backend
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/viadata

  # frontend: build frontend image
  #
  frontend:
    build: ./frontend
    container_name: via_frontend
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
